In [47]:
import trafilatura
import pandas as pd


# 위키백과 페이지 URL
url = "http://www.seoulmetro.co.kr/kr/page.do?menuIdx=354"

# HTML 내용 가져오기
html = trafilatura.fetch_url(url)

# HTML에서 테이블 추출
tables = trafilatura.extract(html, include_tables=True)
tables

'누구나 안전하고 행복하게 이용할 수 있는 서울교통공사가 될 수 있도록 최선을 다하겠습니다.\n|종류\n|교통카드\n|1회권\n|일반\n|\n|교통카드운임에 100원 추가\n|청소년\n|\n|일반 1회권 적용\n|어린이\n|\n|교통카드 운임과 동일\n|우대\n|\n|정기권\n|\n|단체권\n|\n|버스와 환승 이용 시\n(대중교통 통합거리비례제)\n|기본요금\n|10km까지 기본요금-환승 무료\n(서울광역ㆍ경기좌석/직행ㆍ인천좌석/광역 버스는 30km까지)\n단, 이용교통수단 중 높은 기본요금 적용\n|추가요금\n|10km초과시 매5km 까지 마다 100원 가산\n(서울광역ㆍ경기좌석/직행ㆍ인천좌석/광역 버스는 30km초과시)\n|이용거리\n|선ㆍ후불 교통카드\n|1회용 교통카드\n|어른\n|청소년\n|어린이\n|어른(청소년 포함)\n|어린이\n|10Km까지\n|1,400\n|800\n|500\n|1,500\n|500\n|15Km까지\n|1,500\n|880\n|550\n|1,600\n|550\n|20Km까지\n|1,600\n|960\n|600\n|1,700\n|600\n|25Km까지\n|1,700\n|1,040\n|660\n|1,800\n|650\n|30Km까지\n|1,800\n|1,120\n|700\n|1,900\n|700\n|35Km까지\n|1,900\n|1,200\n|750\n|2,000\n|750\n|40Km까지\n|2,000\n|1,280\n|800\n|2,100\n|800\n|45Km까지\n|2100\n|1,360\n|850\n|2,200\n|850\n|50Km까지\n|2,200\n|1,440\n|900\n|2,300\n|900\n|58Km까지\n|2,300\n|1,520\n|950\n|2,400\n|950\n|66Km까지\n|2,400\n|1,600\n|1,000\n|2,500\n|1000\n|74Km까지\n|2,500\n|1,680\n|1,050\n|2,600\n|1,050\n|82Km까지\n|2,600\n|1,760\n|1,100\n|2,700\n|1,100\n|90Km까지\n|2,700\n|1,840\n|1,150\n|2,800\n|1,150\n|98Km까지\n|2,800\n|1,920\n|1,200\n|2,900\n|1,200\n|106Km까지\n|2,900\n|2,000\n|1,250\n|3,000\n|1,250\n|114Km까지\n|3,000\n|2,080\n|1,300\n|3,100\n|1,300\n|122Km까지\n|3,100\n|2,160\n|1,350\n|3,200\n|1,350\n|130Km까지\n|3,200\n|2,240\n|1,400\n|3,300\n|1,400\n|138Km까지\n|3,300\n|2,320\n|1,450\n|3,400\n|1,450\n|146Km까지\n|3,400\n|2,400\n|1,500\n|3,500\n|1,500\n|154Km까지\n|3,500\n|2,480\n|1,550\n|3,600\n|1,550\n|162Km까지\n|3,600\n|2,560\n|1,600\n|3,700\n|1,600\n|170Km까지\n|3,700\n|2,640\n|1,650\n|3,800\n|1,650\n|178Km까지\n|3,800\n|2,720\n|1,700\n|3,900\n|1,700'

In [48]:
table_frame = tables.split('(서울광역ㆍ경기좌석/직행ㆍ인천좌석/광역 버스는 30km초과시)')[1]

In [54]:
lines = table_frame.strip().split('\n')
data = [line.split('|')[1] for line in lines[0:]]

data

['이용거리',
 '선ㆍ후불 교통카드',
 '1회용 교통카드',
 '어른',
 '청소년',
 '어린이',
 '어른(청소년 포함)',
 '어린이',
 '10Km까지',
 '1,400',
 '800',
 '500',
 '1,500',
 '500',
 '15Km까지',
 '1,500',
 '880',
 '550',
 '1,600',
 '550',
 '20Km까지',
 '1,600',
 '960',
 '600',
 '1,700',
 '600',
 '25Km까지',
 '1,700',
 '1,040',
 '660',
 '1,800',
 '650',
 '30Km까지',
 '1,800',
 '1,120',
 '700',
 '1,900',
 '700',
 '35Km까지',
 '1,900',
 '1,200',
 '750',
 '2,000',
 '750',
 '40Km까지',
 '2,000',
 '1,280',
 '800',
 '2,100',
 '800',
 '45Km까지',
 '2100',
 '1,360',
 '850',
 '2,200',
 '850',
 '50Km까지',
 '2,200',
 '1,440',
 '900',
 '2,300',
 '900',
 '58Km까지',
 '2,300',
 '1,520',
 '950',
 '2,400',
 '950',
 '66Km까지',
 '2,400',
 '1,600',
 '1,000',
 '2,500',
 '1000',
 '74Km까지',
 '2,500',
 '1,680',
 '1,050',
 '2,600',
 '1,050',
 '82Km까지',
 '2,600',
 '1,760',
 '1,100',
 '2,700',
 '1,100',
 '90Km까지',
 '2,700',
 '1,840',
 '1,150',
 '2,800',
 '1,150',
 '98Km까지',
 '2,800',
 '1,920',
 '1,200',
 '2,900',
 '1,200',
 '106Km까지',
 '2,900',
 '2,000',
 '1,250',
 '3,000',
 '1,250',
 '114Km까지',
 '3,000',
 '2,080',
 '1,300',
 '3,100',
 '1,300',
 '122Km까지',
 '3,100',
 '2,160',
 '1,350',
 '3,200',
 '1,350',
 '130Km까지',
 '3,200',
 '2,240',
 '1,400',
 '3,300',
 '1,400',
 '138Km까지',
 '3,300',
 '2,320',
 '1,450',
 '3,400',
 '1,450',
 '146Km까지',
 '3,400',
 '2,400',
 '1,500',
 '3,500',
 '1,500',
 '154Km까지',
 '3,500',
 '2,480',
 '1,550',
 '3,600',
 '1,550',
 '162Km까지',
 '3,600',
 '2,560',
 '1,600',
 '3,700',
 '1,600',
 '170Km까지',
 '3,700',
 '2,640',
 '1,650',
 '3,800',
 '1,650',
 '178Km까지',
 '3,800',
 '2,720',
 '1,700',
 '3,900',
 '1,700']

In [57]:
filtered_data = [item for item in data if item not in ['선ㆍ후불 교통카드', '1회용 교통카드']]

print(filtered_data)

['이용거리', '어른', '청소년', '어린이', '어른(청소년 포함)', '어린이', '10Km까지', '1,400', '800', '500', '1,500', '500', '15Km까지', '1,500', '880', '550', '1,600', '550', '20Km까지', '1,600', '960', '600', '1,700', '600', '25Km까지', '1,700', '1,040', '660', '1,800', '650', '30Km까지', '1,800', '1,120', '700', '1,900', '700', '35Km까지', '1,900', '1,200', '750', '2,000', '750', '40Km까지', '2,000', '1,280', '800', '2,100', '800', '45Km까지', '2100', '1,360', '850', '2,200', '850', '50Km까지', '2,200', '1,440', '900', '2,300', '900', '58Km까지', '2,300', '1,520', '950', '2,400', '950', '66Km까지', '2,400', '1,600', '1,000', '2,500', '1000', '74Km까지', '2,500', '1,680', '1,050', '2,600', '1,050', '82Km까지', '2,600', '1,760', '1,100', '2,700', '1,100', '90Km까지', '2,700', '1,840', '1,150', '2,800', '1,150', '98Km까지', '2,800', '1,920', '1,200', '2,900', '1,200', '106Km까지', '2,900', '2,000', '1,250', '3,000', '1,250', '114Km까지', '3,000', '2,080', '1,300', '3,100', '1,300', '122Km까지', '3,100', '2,160', '1,350', '3,200', '1,350', '130Km까지', '3,200', '2,240', '1,400', '3,300', '1,400', '138Km까지', '3,300', '2,320', '1,450', '3,400', '1,450', '146Km까지', '3,400', '2,400', '1,500', '3,500', '1,500', '154Km까지', '3,500', '2,480', '1,550', '3,600', '1,550', '162Km까지', '3,600', '2,560', '1,600', '3,700', '1,600', '170Km까지', '3,700', '2,640', '1,650', '3,800', '1,650', '178Km까지', '3,800', '2,720', '1,700', '3,900', '1,700']

In [63]:
grouped_data = [filtered_data[i:i+6] for i in range(0, len(filtered_data), 6)]

# 데이터프레임으로 변환합니다.
df = pd.DataFrame(grouped_data)
df

          0      1      2      3           4      5
0      이용거리     어른    청소년    어린이  어른(청소년 포함)    어린이
1    10Km까지  1,400    800    500       1,500    500
2    15Km까지  1,500    880    550       1,600    550
3    20Km까지  1,600    960    600       1,700    600
4    25Km까지  1,700  1,040    660       1,800    650
5    30Km까지  1,800  1,120    700       1,900    700
6    35Km까지  1,900  1,200    750       2,000    750
7    40Km까지  2,000  1,280    800       2,100    800
8    45Km까지   2100  1,360    850       2,200    850
9    50Km까지  2,200  1,440    900       2,300    900
10   58Km까지  2,300  1,520    950       2,400    950
11   66Km까지  2,400  1,600  1,000       2,500   1000
12   74Km까지  2,500  1,680  1,050       2,600  1,050
13   82Km까지  2,600  1,760  1,100       2,700  1,100
14   90Km까지  2,700  1,840  1,150       2,800  1,150
15   98Km까지  2,800  1,920  1,200       2,900  1,200
16  106Km까지  2,900  2,000  1,250       3,000  1,250
17  114Km까지  3,000  2,080  1,300       3,100  1,300
18  122Km까지  3,100  2,160  1,350       3,200  1,350
19  130Km까지  3,200  2,240  1,400       3,300  1,400
20  138Km까지  3,300  2,320  1,450       3,400  1,450
21  146Km까지  3,400  2,400  1,500       3,500  1,500
22  154Km까지  3,500  2,480  1,550       3,600  1,550
23  162Km까지  3,600  2,560  1,600       3,700  1,600
24  170Km까지  3,700  2,640  1,650       3,800  1,650
25  178Km까지  3,800  2,720  1,700       3,900  1,700

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       26 non-null     object
 1   1       26 non-null     object
 2   2       26 non-null     object
 3   3       26 non-null     object
 4   4       26 non-null     object
 5   5       26 non-null     object
dtypes: object(6)
memory usage: 1.3+ KB

In [65]:
df.columns = df.iloc[0]
df = df.drop(0)
df

0      이용거리     어른    청소년    어린이 어른(청소년 포함)    어린이
1    10Km까지  1,400    800    500      1,500    500
2    15Km까지  1,500    880    550      1,600    550
3    20Km까지  1,600    960    600      1,700    600
4    25Km까지  1,700  1,040    660      1,800    650
5    30Km까지  1,800  1,120    700      1,900    700
6    35Km까지  1,900  1,200    750      2,000    750
7    40Km까지  2,000  1,280    800      2,100    800
8    45Km까지   2100  1,360    850      2,200    850
9    50Km까지  2,200  1,440    900      2,300    900
10   58Km까지  2,300  1,520    950      2,400    950
11   66Km까지  2,400  1,600  1,000      2,500   1000
12   74Km까지  2,500  1,680  1,050      2,600  1,050
13   82Km까지  2,600  1,760  1,100      2,700  1,100
14   90Km까지  2,700  1,840  1,150      2,800  1,150
15   98Km까지  2,800  1,920  1,200      2,900  1,200
16  106Km까지  2,900  2,000  1,250      3,000  1,250
17  114Km까지  3,000  2,080  1,300      3,100  1,300
18  122Km까지  3,100  2,160  1,350      3,200  1,350
19  130Km까지  3,200  2,240  1,400      3,300  1,400
20  138Km까지  3,300  2,320  1,450      3,400  1,450
21  146Km까지  3,400  2,400  1,500      3,500  1,500
22  154Km까지  3,500  2,480  1,550      3,600  1,550
23  162Km까지  3,600  2,560  1,600      3,700  1,600
24  170Km까지  3,700  2,640  1,650      3,800  1,650
25  178Km까지  3,800  2,720  1,700      3,900  1,700

In [66]:
df = df.apply(lambda x: x.str.replace(',', ''))
df

0      이용거리    어른   청소년   어린이 어른(청소년 포함)   어린이
1    10Km까지  1400   800   500       1500   500
2    15Km까지  1500   880   550       1600   550
3    20Km까지  1600   960   600       1700   600
4    25Km까지  1700  1040   660       1800   650
5    30Km까지  1800  1120   700       1900   700
6    35Km까지  1900  1200   750       2000   750
7    40Km까지  2000  1280   800       2100   800
8    45Km까지  2100  1360   850       2200   850
9    50Km까지  2200  1440   900       2300   900
10   58Km까지  2300  1520   950       2400   950
11   66Km까지  2400  1600  1000       2500  1000
12   74Km까지  2500  1680  1050       2600  1050
13   82Km까지  2600  1760  1100       2700  1100
14   90Km까지  2700  1840  1150       2800  1150
15   98Km까지  2800  1920  1200       2900  1200
16  106Km까지  2900  2000  1250       3000  1250
17  114Km까지  3000  2080  1300       3100  1300
18  122Km까지  3100  2160  1350       3200  1350
19  130Km까지  3200  2240  1400       3300  1400
20  138Km까지  3300  2320  1450       3400  1450
21  146Km까지  3400  2400  1500       3500  1500
22  154Km까지  3500  2480  1550       3600  1550
23  162Km까지  3600  2560  1600       3700  1600
24  170Km까지  3700  2640  1650       3800  1650
25  178Km까지  3800  2720  1700       3900  1700

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 1 to 25
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   이용거리        25 non-null     object
 1   어른          25 non-null     object
 2   청소년         25 non-null     object
 3   어린이         25 non-null     object
 4   어른(청소년 포함)  25 non-null     object
 5   어린이         25 non-null     object
dtypes: object(6)
memory usage: 1.3+ KB

In [70]:
df[['어른', '청소년', '어린이']] = df[['어른', '청소년', '어린이']].astype(int)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 1 to 25
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   이용거리        25 non-null     object
 1   어른          25 non-null     int64
 2   청소년         25 non-null     int64
 3   어린이         25 non-null     int64
 4   어른(청소년 포함)  25 non-null     object
 5   어린이         25 non-null     int64
dtypes: int64(4), object(2)
memory usage: 1.3+ KB

In [73]:
df_price = df.iloc[:, :4]
df_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 1 to 25
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이용거리    25 non-null     object
 1   어른      25 non-null     int64
 2   청소년     25 non-null     int64
 3   어린이     25 non-null     int64
dtypes: int64(3), object(1)
memory usage: 932.0+ bytes

In [74]:
import mysql.connector


yespa_db = mysql.connector.connect(
    host = 'database-1.c3ieyo8m4v9o.ap-northeast-2.rds.amazonaws.com',
    port = 3306,
    user = 'eda_team',
    database = 'eda_project',
    password = '123456'
)

cursor = yespa_db.cursor(buffered=True)
cursor.execute("CREATE TABLE metro_price_info(거리 VARCHAR(16), 어른 INT, 청소년 INT, 어린이 INT)")
sql = "INSERT INTO metro_price_info VALUES(%s,%s,%s,%s)"

for i, row in df_price.iterrows():
    cursor.execute(sql, tuple(row))
    print(tuple(row))
    yespa_db.commit()
    
yespa_db.close()

('10Km까지', 1400, 800, 500)
('15Km까지', 1500, 880, 550)
('20Km까지', 1600, 960, 600)
('25Km까지', 1700, 1040, 660)
('30Km까지', 1800, 1120, 700)
('35Km까지', 1900, 1200, 750)
('40Km까지', 2000, 1280, 800)
('45Km까지', 2100, 1360, 850)
('50Km까지', 2200, 1440, 900)
('58Km까지', 2300, 1520, 950)
('66Km까지', 2400, 1600, 1000)
('74Km까지', 2500, 1680, 1050)
('82Km까지', 2600, 1760, 1100)
('90Km까지', 2700, 1840, 1150)
('98Km까지', 2800, 1920, 1200)
('106Km까지', 2900, 2000, 1250)
('114Km까지', 3000, 2080, 1300)
('122Km까지', 3100, 2160, 1350)
('130Km까지', 3200, 2240, 1400)
('138Km까지', 3300, 2320, 1450)
('146Km까지', 3400, 2400, 1500)
('154Km까지', 3500, 2480, 1550)
('162Km까지', 3600, 2560, 1600)
('170Km까지', 3700, 2640, 1650)
('178Km까지', 3800, 2720, 1700)